UID = "906C8804"
Name = "B18BDDB1"
TriggerScript = """
ifNpcModifierHasValue.1
say.<Unfortunately this chest is empty!>.0
waitForUser
exit
endIf
say.<Open chest?>.1
choice.0.<Yes>
choice.1.<No>
waitForUser
label.0
createDynamicModel.0.-1.-1
ifNpcModifierHasValue.110
subGame.0.1.10
waitForUser
exit
endIf
ifNpcModifierHasValue.170
subGame.0.1.70
waitForUser
exit
endIf
ifNpcModifierHasValue.171
subGame.0.1.71
waitForUser
exit
endIf
ifNpcModifierHasValue.172
subGame.0.1.72
waitForUser
exit
endIf
ifNpcModifierHasValue.173
subGame.0.1.73
waitForUser
exit
endIf
ifNpcModifierHasValue.2
givePlayerCards.1.0.2
endIf
ifNpcModifierHasValue.3
givePlayerCards.1.0.3
endIf
ifNpcModifierHasValue.4
givePlayerCards.1.0.4
endIf
ifNpcModifierHasValue.5
givePlayerCards.1.0.5
endIf
ifNpcModifierHasValue.6
givePlayerCards.1.0.6
endIf
ifNpcModifierHasValue.7
givePlayerCards.1.0.7
endIf
ifNpcModifierHasValue.8
givePlayerCards.1.0.8
endIf
ifNpcModifierHasValue.10
label.10
givePlayerCards.1.0.10
endIf
ifNpcModifierHasValue.13
givePlayerCards.1.0.13
endIf
ifNpcModifierHasValue.17
givePlayerCards.1.0.17
endIf
ifNpcModifierHasValue.18
givePlayerCards.1.0.18
endIf
ifNpcModifierHasValue.19
givePlayerCards.1.0.19
endIf
ifNpcModifierHasValue.20
givePlayerCards.1.0.20
endIf
ifNpcModifierHasValue.21
givePlayerCards.1.0.21
endIf
ifNpcModifierHasValue.30
givePlayerCards.1.0.30
endIf
ifNpcModifierHasValue.51
subGame.0.1.51
waitForUser
exit
label.51
givePlayerCards.1.0.51
endIf
ifNpcModifierHasValue.52
givePlayerCards.1.0.52
endIf
ifNpcModifierHasValue.53
subGame.0.1.53
waitForUser
exit
label.53
givePlayerCards.1.0.53
endIf
ifNpcModifierHasValue.54
givePlayerCards.1.0.54
endIf
ifNpcModifierHasValue.55
givePlayerCards.1.0.55
endIf
ifNpcModifierHasValue.56
givePlayerCards.1.0.56
endIf
ifNpcModifierHasValue.57
subGame.0.1.57
waitForUser
exit
label.57
givePlayerCards.1.0.57
endIf
ifNpcModifierHasValue.60
givePlayerCards.1.0.60
endIf
ifNpcModifierHasValue.61
givePlayerCards.1.0.61
endIf
ifNpcModifierHasValue.62
givePlayerCards.1.0.62
endIf
ifNpcModifierHasValue.63
givePlayerCards.1.0.63
endIf
ifNpcModifierHasValue.64
givePlayerCards.1.0.64
endIf
ifNpcModifierHasValue.65
givePlayerCards.1.0.65
endIf
ifNpcModifierHasValue.66
givePlayerCards.1.0.66
endIf
ifNpcModifierHasValue.67
givePlayerCards.1.0.67
endIf
ifNpcModifierHasValue.70
label.70
givePlayerCards.2.0.70
endIf
ifNpcModifierHasValue.71
label.71
givePlayerCards.1.0.71
endIf
ifNpcModifierHasValue.72
label.72
givePlayerCards.1.0.72
endIf
ifNpcModifierHasValue.73
label.73
givePlayerCards.1.0.73
endIf
setCamera.1007
playAnimation.14.0
playSound.1
setNpcModifier.-1.-1.1
delay.10
setCamera.1006
label.1
exit"""
InitScript = """
setNpcType.4
setModel.i002si02
ifNpcModifierHasValue.1
playAnimation.14.0
endIf"""
