UID = "475CE2A4"
Name = "B18BDDB1"
TriggerScript = """
ifNpcModifierHasValue.1
say.<Unfortunately this chest is empty!>.0
waitForUser
exit
endIf
say.<Open casket?>.1
choice.0.<Yes>
choice.1.<No>
waitForUser
label.0
setCamera.1007
playAnimation.14.0
createDynamicModel.0.-1.-1
playSound.1
ifNpcModifierHasValue.0
givePlayerCards.1.0.0
endIf
ifNpcModifierHasValue.1
givePlayerCards.1.0.1
endIf
ifNpcModifierHasValue.2
givePlayerCards.1.0.2
endIf
ifNpcModifierHasValue.3
givePlayerCards.1.0.3
endIf
ifNpcModifierHasValue.17
givePlayerCards.1.0.17
endIf
ifNpcModifierHasValue.20
givePlayerCards.1.0.20
endIf
ifNpcModifierHasValue.21
givePlayerCards.1.0.21
endIf
ifNpcModifierHasValue.30
givePlayerCards.1.0.30
endIf
ifNpcModifierHasValue.51
givePlayerCards.1.0.51
endIf
ifNpcModifierHasValue.52
givePlayerCards.1.0.52
endIf
ifNpcModifierHasValue.53
givePlayerCards.1.0.53
endIf
ifNpcModifierHasValue.54
givePlayerCards.1.0.54
endIf
ifNpcModifierHasValue.55
givePlayerCards.1.0.55
endIf
ifNpcModifierHasValue.56
givePlayerCards.1.0.56
endIf
ifNpcModifierHasValue.60
givePlayerCards.1.0.60
endIf
ifNpcModifierHasValue.63
givePlayerCards.1.0.63
endIf
ifNpcModifierHasValue.64
givePlayerCards.1.0.64
endIf
ifNpcModifierHasValue.65
givePlayerCards.1.0.65
endIf
ifNpcModifierHasValue.66
givePlayerCards.1.0.66
endIf
ifNpcModifierHasValue.71
givePlayerCards.1.0.71
endIf
ifNpcModifierHasValue.72
givePlayerCards.1.0.72
endIf
setNpcModifier.-1.-1.1
delay.10
setCamera.1006
label.1"""
InitScript = """
setNpcType.4
setModel.i003si03
ifNpcModifierHasValue.1
playAnimation.14.0
endIf"""
