UID = "CD6BA214"
Name = "6E781E01"
TriggerScript = """
setCamera.1002
playAnimation.13.-1
gotoRandomLabel.3.10
label.10
say.<
    Hello, Amy.
    Did you have a good trip?
>.0
goto.13
label.11
say.<Hello, Amy.>.0
goto.13
label.12
say.<Hello, Fairy Mistress.>.0
goto.13
label.13
waitForUser
label.0
say.<What else do you want to find out about the Fairy Masters?>.1
choice.1.<Fairy bag>
choice.2.<Tournaments>
choice.3.<Nothing more>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    Your fairy bag can hold up to {4*five fairies} at a time.
    You will find all other fairies at your home.
    Since you're from the human world, your fairies should be there, too.
    
>
waitForUser
goto.0
label.2
setTalkLabels.-1.-1.2
talk.<
    The best {4*Fairy Masters} used to meet in the legendary {4*Realm of Clouds}.
    There is an ancient {4*arena} there, in which only the very best Fairy Masters were allowed to fight.
    But that was a long time ago, and few masters remember it now.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    I myself have stopped travelling, and my {4*brother} over there only catches very weak fairies.
    They're fine for training, but not much good in an actual duel.
>
waitForUser
goto.0
label.3
exit"""
InitScript = """
setModel.g202s22m
movementSpeed.10
defaultWizForm.0.0.4"""
UpdateScript = """
label.0
moveSystem.1.2
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.-1
lookAtPlayer.90.1
goto.0"""
