UID = "5AC06084"
Name = "389D7EB1"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Human Amy, Eirik the Dwarf greets you.>.0
waitForUser
ifPlayerHasCards.1.0.22
setTalkLabels.-1.-1.2
talk.<
    I still can't believe the {4*Druid} caused the chaos in Zanzarah! So he has locked up our Dwarf Master Quinlin and blamed us dwarves?
>
waitForUser
exit
endIf
ifPlayerHasCards.1.0.26
setTalkLabels.-1.-1.2
talk.<
    You found the dwarf artefact with the leader of the {4*Shadow Elves}?
    Now the whole of Zanzarah will believe we summoned the Shadow Elves.
>
waitForUser
exit
endIf
setTalkLabels.-1.-1.2
talk.<
    There is a legend of the {4*perfect fairy combination} among us dwarves.
    I'm still looking for this invincible combination of fairies.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<Every kind of fairy has their own {4*strengths} and {4*weaknesses}, but it is only in the right combination that your fairy's abilities become important.>
waitForUser"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
