UID = "453A1534"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
ifPlayerHasCards.1.0.22
say.<You saved the lost leader!>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    How could the Druid lock up our Dwarf Master?
    You need to thwart the dark plans of the Druid and eliminate his {4*Guard}.
>
waitForUser
goto.0
endIf
say.<
    Hello, human girl.
    
>.0
waitForUser
label.0
setTalkLabels.1.2.1
talk.<I'll trade {4*one crystal} for {4*seven gold coins}.>
waitForUser
label.1
ifPlayerHasCards.7.0.4
removePlayerCards.7.0.4
setTalkLabels.-1.-1.0
talk.<
    A deal is a deal.
    Here's my second crystal.
    Now I've only got {4*one crystal} left.
>
waitForUser
givePlayerCards.1.0.6
changeDatabase.72861934
exit
endIf
setTalkLabels.-1.-1.0
talk.<
    What do you think you're doing?
    You don't have {4*seven gold coins}!
>
waitForUser
exit
label.2
exit"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
