UID = "36C11DB4"
Name = "1C1716B1"
TriggerScript = """
deployNpcAtTrigger.73.1
setCamera.3002
changeWaypoint.21.22
changeWaypoint.22.23
changeWaypoint.23.24
changeWaypoint.24.-1
playAnimation.13.-1
say.<Welcome to the next fight of the tournament.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Thank you for bringing me my favourite fairy.
    It's the best fairy in my collection.
    With its help, I will hunt down {4*Quinlin} and all the other traitorous dwarves.
    So let us fight for the card!
>
waitForUser
setCamera.1006
fight.-1.0
exit"""
InitScript = """
setModel.g203s23m
defaultWizForm.26.3.31
defaultWizForm.11.2.38
defaultWizForm.21.1.34
defaultWizForm.68.0.39"""
UpdateScript = """
label.0
idle
ifTriggerIsActive.69
startPrelude
endIf
goto.0"""
DefeatedScript = """
setCamera.3003
setTalkLabels.-1.-1.0
talk.<
    I lost in spite of my {4*Segbuzz}?
    Perhaps it's not as good as I always thought it was.
    Take it back, I'm going to go looking for a new favourite fairy.
>
waitForUser
givePlayerCards.1.2.68
changeWaypoint.-1.25
changeWaypoint.25.26
changeWaypoint.26.27
changeWaypoint.27.28
removeNpc"""
VictoriousScript = "killPlayer"
