UID = "9FB22894"
Name = "0FDF8F91"
TriggerScript = """
setCamera.1000
playAnimation.12.-1
say.<...>.0
waitForUser
gotoRandomLabel.2.5
label.5
setTalkLabels.1.2.1
talk.<
    Somehow, I seem to be forever waiting for something good to happen in the swamp, but the Shadow Elves are lurking around instead.
    I'm sure things must be very different in the {4*human world}.
>
waitForUser
label.6
setTalkLabels.1.2.1
talk.<
    This weather in the swamp makes me melancholic.
    And now the {4*Shadow Elves} are here as well.
    Your {4*human world} must be much nicer, isn't it?
>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    I wish I was a human as well! Then I could have adventures like yours and travel through foreign countries.
>
waitForUser
exit
label.2
setTalkLabels.-1.-1.0
talk.<
    The {4*human world} is boring?
    I don't believe that.
>
waitForUser
exit"""
InitScript = "setModel.g003s03m"
UpdateScript = """
label.0
idle
moveSystem.1.3
gotoRandomLabel.2.0
goto.0
label.1
playAnimation.0.90
goto.0"""
