UID = "1D5352B4"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
ifNpcModifierHasValue.0
goto.1
endIf
say.<You again ...>.0
waitForUser
talk.<Leave me alone, I've had enough.>
waitForUser
exit
label.1
say.<What's a human doing in this forest?>.0
waitForUser
setTalkLabels.10.11.1
talk.<
    You should be careful, the fairies in this part of {4*Zanzarah} are very aggressive.
    Try to beat one of my fairies, then you'll know if you're experienced enough, all right?
>
waitForUser
label.10
setCamera.1006
fight.-1.0
exit
label.11
exit"""
InitScript = """
setModel.g300s30m
movementSpeed.14
defaultWizForm.1.0.9
defaultWizForm.9.1.11
defaultWizForm.2.2.9"""
UpdateScript = "lookAtPlayer.0.1"
DefeatedScript = """
setCamera.1000
setNpcModifier.-1.-1.1
setTalkLabels.-1.-1.0
talk.<
    I don't believe it! A human has managed to beat my fairies! Whatever next?!
>
waitForUser"""
