UID = "3243CA14"
Name = "BDE38F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Welcome to our beautiful garden!>.0
waitForUser
ifNpcModifierHasValue.1
talk.<
    Did you ever see anything more beautiful than these magic silver spheres?
    However, they can't be used to catch all fairies.
    You'll need special spheres to catch stronger, more experienced fairies.
>
waitForUser
exit
endIf
ifTriggerIsEnabled.27
setTalkLabels.-1.-1.0
talk.<
    Do you see that lovely {4*magic sphere}?
    I'd like to get it, but a particularly aggressive fairy lives right beside it ...
>
waitForUser
exit
else
setTalkLabels.0.1.1
talk.<
    I would love to have a {4*silver sphere} that I can catch a fairy with, but they're really hard to find.
    Would you give me one?
    You can have my Water Fairy in exchange!
>
waitForUser
exit
endIf
label.0
setTalkLabels.-1.-1.0
ifPlayerHasCards.1.0.17
talk.<
    Oh how lovely! Here, have my fairy!
>
givePlayerCards.1.2.6
removePlayerCards.1.0.17
removeWizForms
setNpcModifier.-1.-1.1
waitForUser
exit
else
talk.<Hm, you don't even have a {4*silver sphere}!>
waitForUser
endIf
exit
label.1"""
InitScript = """
setModel.g205s21m
ifNpcModifierHasValue.0
defaultWizForm.6.0.1
endIf"""
UpdateScript = """
ifTriggerIsEnabled.27
lookAtTrigger.-1.27
else
lookAtPlayer.-1.1
endIf"""
