UID = "84E22024"
Name = "7B2D8F91"
TriggerScript = """
playAnimation.13.-1
setCamera.1000
say.<What a pleasant visit.>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.0
talk.<
    Have you caught any {4*Tinefol} fairies yet?
    You can use various {4*evolutionary stones} to change them into different forms.
    However, those stones aren't easy to get.
>
waitForUser
exit
endIf
setTalkLabels.-1.-1.2
talk.<
    I haven't seen any Fairy Masters for ages.
    The {4*Shadow Elves} drove them all away! That's why I withdrew into this cave.
    My favourite fairies and I can live peacefully here.
>
waitForUser
setTalkLabels.0.1.1
talk.<
    But it's been getting a bit boring lately.
    We haven't had any fairy duels for ages, and we really miss the practice.
    Do you fancy a little fight?
>
waitForUser
label.0
setCamera.1006
fight.-1.0
exit
label.1
exit"""
InitScript = """
setModel.d004s00m
defaultWizForm.57.0.30
defaultWizForm.58.1.25
defaultWizForm.59.2.34
defaultWizForm.60.3.19"""
UpdateScript = "lookAtPlayer.-1.1"
DefeatedScript = """
setCamera.1000
setNpcModifier.-1.-1.1
setTalkLabels.-1.-1.2
talk.<
    Great, your fairies are really impressive! Have you noticed my extraordinary collection?
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    They were all {4*Tinefol} Nature Fairies.
    But I managed to change them into all kinds of creatures using {4*evolutionary stones}.
    Maybe you should give it a try yourself!
>
waitForUser
exit"""
