UID = "399C7404"
Name = "7B2D8F91"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
say.<Welcome to Monagham, Amy.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Sometimes I hear evil rumours about us dwarves and the Druid.
    But I'm not interested in them.
    My only interest is in crystals.
>
waitForUser"""
InitScript = "setModel.d000s00m"
UpdateScript = "lookAtPlayer.-1.1"
