UID = "E856B204"
Name = "0E2216B1"
TriggerScript = """
ifNumberOfNpcsIs.1.149DEE04
goto.40
endIf
playAnimation.13.-1
setCamera.1000
say.<
    Hello, Amy.
    Have you news of my friend, Lasse the Dwarf?
>.0
waitForUser
ifPlayerHasCards.1.0.22
goto.10
endIf
ifPlayerHasCards.1.0.25
goto.30
endIf
label.0
say.<Do you have a friend in your human world?>.1
choice.1.<Yes>
choice.2.<No>
choice.3.<I won't tell you.>
waitForUser
label.1
setTalkLabels.-1.-1.0
talk.<
    Then you can imagine how much I miss {4*my Lasse}.
    I've looked for him, but my fairies are simply too weak for a long trip.
>
waitForUser
exit
label.2
setTalkLabels.-1.-1.2
talk.<
    Things are nearly the same for me at the moment.
    {4*Lasse} is travelling all the time.
    If he doesn't find his father, the {4*Dwarf Master}, he'll carry on searching forever.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<But I don't want to have to wait for him forever!>
waitForUser
exit
label.3
exit
label.10
setTalkLabels.-1.-1.2
talk.<
    You're on the right path, Amy.
    Use the {4*iron key} and find the {4*Guard}.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    I would be eternally grateful if you could free my friend Lasse the Dwarf from the hands of the Druid.
    If you want to save him, hurry to the {4*White Cathedral}!
>
waitForUser
goto.0
label.30
say.<The Druid has captured Lasse?>.0
waitForUser
setTalkLabels.-1.-1.2
talk.<
    My Lasse is no thief! Our leader, the {4*Dwarf Master}, can surely prove that.
>
waitForUser
talk.<
    You can only prove Lasse's innocence by finding out who's really behind all these intrigues.
    Find our leader, the {4*Dwarf Master}!
>
waitForUser
goto.0
label.40
deployNpcAtTrigger.5.1
setCamera.3001
playAnimation.13.-1
say.<Welcome to our small hut, Amy.>.0
waitForUser
setTalkLabels.-1.-1.0
talk.<
    Thank you for rescuing Lasse from the Druid.
    Now I can go on my travels and Lasse will look after our house.
>
waitForUser
changeWaypoint.1.2
changeWaypoint.2.3
removeNpc"""
InitScript = """
setModel.g000s00m
wizform.1.1.2"""
UpdateScript = """
deployNpcAtTrigger.40.0
lookAtPlayer.-1.-1"""
