UID = "D2600234"
Name = "5B6A3F31"
TriggerScript = """
setCamera.1000
playAnimation.13.-1
playPlayerAnimation.15.-1
say.<Amy, it's good to see you.>.0
waitForUser
ifNpcModifierHasValue.1
setTalkLabels.-1.-1.2
talk.<
    Welcome to the little village of Endeva.
    As you can see, it's inhabited by peaceful {4*Forest Elves}, though they have seemed somewhat nervous of late.
    Endeva is an ideal place to begin your travels from.
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    This friendly woodland elf right beside me is ideal for training inexperienced fairies.
    You'll find useful utensils in Endeva's herb shop.
    Arm yourself well, before you start to travel.
>
waitForUser
exit
else
setTalkLabels.-1.-1.2
talk.<
    We have been waiting for you a long time.
    {4*Owls} were dispatched from the forests throughout {4*Zanzarah} to help you on your quest.
    If ever you meet one of us, don't hesitate to ask questions.
    
>
waitForUser
setTalkLabels.-1.-1.0
talk.<
    But please remember that none of us knows the whole truth.
    Our knowledge is limited to the region we were sent to.
>
waitForUser
setNpcModifier.-1.-1.1
endIf"""
InitScript = "setModel.w003s03m"
UpdateScript = "lookAtPlayer.0.0"
